mod 'puppetlabs-docker', '3.2.0'
mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-reboot', '2.0.0'
mod 'puppetlabs-powershell', '2.2.0'
mod 'puppetlabs-apt', '6.2.1'
mod 'puppetlabs-translate', '1.1.0'
